backend:
  name: git-gateway
  branch: projects

media_folder: public/images
public_folder: /images

publish_mode: editorial_workflow # For Drafts

collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Project" # Used in the UI
    folder: "content/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{project}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Meta: Description", name: "metaDescription", widget: "text"}
      - {label: "Open Graph: Website-URL", name: "ogUrl", widget: "string"}
      - {label: "Open Graph: Title", name: "ogTitle", widget: "string"}
      - {label: "Open Graph: Description", name: "ogDescription", widget: "text"}
      - {label: "Open Graph: Image", name: "ogImgUrl", widget: "image"}
      - {label: "Open Graph: Image Alt-Text", name: "ogImgAlt", widget: "string"}
      - {label: "Headerimage", name: "headerImg", widget: "image"}
      - {label: "Headerimage Width", name: "headerImgWidth", widget: "number"}
      - {label: "Headerimage Height", name: "headerImgHeight", widget: "number"}
      - {label: "Headerimage Alt-Text", name: "headerImageAlt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
